// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvmNUWxnwVDgHRXfXZr6tV5cMvsQlIfUE',
    appId: '1:190588121547:web:ecf311b1cb30b1bd21464e',
    messagingSenderId: '190588121547',
    projectId: 'mygestor-dac62',
    authDomain: 'mygestor-dac62.firebaseapp.com',
    storageBucket: 'mygestor-dac62.firebasestorage.app',
    measurementId: 'G-JZXEMP3106',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxAdUq-nimAqtGSRls-neMOSi2gwdQHWo',
    appId: '1:190588121547:android:e3a21ea69f9fd98921464e',
    messagingSenderId: '190588121547',
    projectId: 'mygestor-dac62',
    storageBucket: 'mygestor-dac62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAy7znWIXlSkNr4LDJYUWgzHJYqdxAUtM',
    appId: '1:190588121547:ios:be402a813943719a21464e',
    messagingSenderId: '190588121547',
    projectId: 'mygestor-dac62',
    storageBucket: 'mygestor-dac62.firebasestorage.app',
    iosBundleId: 'com.example.mygestor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAy7znWIXlSkNr4LDJYUWgzHJYqdxAUtM',
    appId: '1:190588121547:ios:be402a813943719a21464e',
    messagingSenderId: '190588121547',
    projectId: 'mygestor-dac62',
    storageBucket: 'mygestor-dac62.firebasestorage.app',
    iosBundleId: 'com.example.mygestor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvmNUWxnwVDgHRXfXZr6tV5cMvsQlIfUE',
    appId: '1:190588121547:web:adb8dd7a9b1472cb21464e',
    messagingSenderId: '190588121547',
    projectId: 'mygestor-dac62',
    authDomain: 'mygestor-dac62.firebaseapp.com',
    storageBucket: 'mygestor-dac62.firebasestorage.app',
    measurementId: 'G-55P5TK916F',
  );
}
